### ISSUE TITLE
Question on goals: Translating resources other than Ingress v1 to Gateway API resources

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes-sigs/ingress2gateway#1]
Wanted to raise a question on clarifying the goals of this project:

Can we consider building something that supports converting more types of resources to Gateway API configuration? (e.g. Contour's HTTPProxy or Knative's IngressRule, etc.)

This may take many forms, for example:
- "plugin" capability for implementation specific conversion logic to live elsewhere
- conversion logic for different CRDs to live in this repo, contributed by various communities
- other ideas

In case it is useful, here is a quick spike I did on converting Contour's HTTPProxy to Gateway API: https://github.com/sunjayBhatia/proxy2gateway

**Comment by shaneutt** [comment]
I don't speak for @robscott at all, but for myself I think it would be useful to have these kinds of conversions in here too, if nothing else just to have the knowledge and tooling for converting pre-gateway APIs to gateway in one place and not spread out across the internet.

**Comment by youngnick** [comment]
From #2, it seems like the consensus is:
- We're going to to Ingress and some common annotations _first_.
- We _may_ do other CRDs _later_, but
- In all these cases, the Gateway API objects that are output must use the existing spec _only_, _no annotations allowed_.

If so, I love this plan, and I'm excited to be a part of it.

**Comment by robscott** [comment]
I think now that #2 is merged, we can close this out, let me know if I missed anything.
