### ISSUE TITLE
Check how we can configure the repo to always squash PRs on merge

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/ingress2gateway#105]
**What you expected to happen**:
see title

/kind cleanup

**Comment by levikobi** [comment]
I'm not strictly against it, but I wonder if we really want it.
Is this something common to do?
I wonder if it will suppress contributors from taking on big contributions, as everything will count as a single commit at the end of the day. 

One thing I will say is that I definitely agree with squashing PRs with unnecessarily large amounts of commits. Maybe we should keep the decision to the approvers based on each PR?

**Comment by LiorLieberman** [comment]
It is a common practice, yeah.

I personally don't remember to state that on every PR, but what happens is that a lot of commits in PRs are "fix", "typo" etc.

The commit stats is a valid point, I am not sure how it is calculated actually. @shaneutt @robscott can you advise on this?

**Comment by mlavacca** [comment]
+1 on this one. I think that having a single commit per PR would make commit history cleaner. As a first step, we could pose ourselves with the rule of manually squashing before merging.

**Comment by robscott** [comment]
I personally think we should do this on both Gateway API repos. The official Kubernetes guidance is to manually squash commits before merging (https://www.kubernetes.dev/docs/guide/github-workflow/#squash-commits). Here's how to configure this per-repo: https://github.com/kubernetes/test-infra/blob/e16f5d38d042d53cbd38149ee227ce019ce60a1d/config/prow/config.yaml#L798-L818.

I'm open to @shaneutt's feedback here, but my opinion is that a single commit per PR should be the default, and if some PRs justify multiple commits, that can be manually changed on those PRs by changing the label. In any case, I think you're free to change any settings you'd like on i2gw repo, but I'll probably need to circulate this a bit more broadly to make the same change on the main gateway-api repo.

**Comment by shaneutt** [comment]
I agree that squash should be the default. There may be times when bigger PRs are needed, or when a patch contains several distinct objectives that cleanly encapsulate as separate actual commits and/or make it easier to understand the process of a change. I think we should default to squash, but remain open to suggestion rather than having a hard and fast rule.

**Comment by LiorLieberman** [comment]
Sounds like we have a consensus. I will go ahead and open a PR to make squash the default for i2gw. 

Feel free to shout if you have any objections.

**Comment by LiorLieberman** [comment]
ref: https://github.com/kubernetes/test-infra/pull/31518
