### ISSUE TITLE
Add Apache APISIX provider

### ISSUE THREAD

**Issue by pottekkat** [kubernetes-sigs/ingress2gateway#107]
**What would you like to be added**:

Add a provider to translate custom annotations and CRDs from [Apache APISIX](https://apisix.apache.org/docs/ingress-controller/getting-started/).

**Why this is needed**:

To help Ingress and CRD users of APISIX migrate easily to the Gateway API.

**Comment by mlavacca** [comment]
This is great @pottekkat! Let us know if you need any help in implementing the provider

**Comment by pottekkat** [comment]
I implemented a basic provider as a start. We are still working to improve our Gateway API support and plan to add more features to the provider.

**Comment by LiorLieberman** [comment]
@pottekkat are you planning to implement more parts of APISIX?

**Comment by pottekkat** [comment]
@LiorLieberman Yes. As the Gateway API support in APISIX improves, I/other APISIX maintainers will add more here.

**Comment by LiorLieberman** [comment]
awesome, do you want to close this issue as done and reopen a new one for specific features then?

**Comment by LiorLieberman** [comment]
Also can you add APISIX link in the main readme same as other providers?

**Comment by pottekkat** [comment]
@LiorLieberman Yes, we can close this issue and open specific issues to add other features to the provider. Opened another PR to update the readme and the provider guide: https://github.com/kubernetes-sigs/ingress2gateway/pull/123
