### ISSUE TITLE
Find a good use of i2gw.InputResources or deprecate it

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/ingress2gateway#113]
**What would you like to be added**:
We need to revisit the decision to use `i2gw.InputResources` struct or deprecate it altogether.

**Why this is needed**:
Currently this struct only holds a list of Ingresses, I couldn't think of a reason we will need other resources as input resources. 
I think this was added originally to be able to support CRD propagation to providers but since we move to a "fetch and store" per provider logic we need to revisit whether this is needed. 

Another sub task that comes with it is changing `ToGatewayAPI` function signature  on the Provider interface as the input resources are no longer in use after https://github.com/kubernetes-sigs/ingress2gateway/pull/112

- [ ] Find a good use of i2gw.InputResources or deprecate it
- [ ] Remove input resources from [ToGatewayAPI](https://github.com/kubernetes-sigs/ingress2gateway/blob/654e76fa2ec341b9eaf9f7ba42f12e3305c7b993/pkg/i2gw/provider.go#L73C2-L73C14) function.

**Comment by levikobi** [comment]
I can't think of a reason either now that we're fetching the resources at the provider level. Let's go ahead and remove it to keep things clean.
/assign

**Comment by YTGhost** [comment]
Hi, I'm interested in this issue.
/assign

**Comment by YTGhost** [comment]
I feel the same way about `i2gw.InputResources`, we could just pass the list of Ingresses instead of wrapping it with `i2gw.InputResources` again.
