### ISSUE TITLE
Execution fails when CRDs are not installed in the cluster

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/ingress2gateway#138]
**What happened**:
When running the tool without `--providers` flag, it defaults to all providers. Then, when istio provider attempts to read its CRs, it fails the execution

**What you expected to happen**:
If I am not specifying istio as the desired provider, execution should work regardless of whether I have the CRDs installed or not

**How to reproduce it (as minimally and precisely as possible)**:
Run `ingress2gateway print` in a cluster without istio CRDs intalled.

Here is the error
```
./ingress2gateway print
Error: failed to read istio resources from the cluster: failed to read resources from cluster: failed to read gateways: failed to list istio gateways: failed to get API group resources: unable to retrieve the complete list of server APIs: networking.istio.io/v1beta1: the server could not find the requested resource
```

Two suggestion in mind for how to address this:
1) Enforce to specify `--providers`, and not default to all providers
2) Fail soft with a warning if the provider specified is not the provider whose CRDs are not installed

/assign @dpasiukevich 
/cc @levikobi 
/cc @mlavacca

**Comment by YTGhost** [comment]
@LiorLieberman Hi, I'm interested in this issue. If @dpasiukevich  doesn't have enough bandwidth to handle this issue, I think I could try to help resolve it :)

**Comment by dpasiukevich** [comment]
@YTGhost would be great if you'd help with this issue!

/assign @YTGhost
