### ISSUE TITLE
Fix/update goreleaser

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/ingress2gateway#206]
goreleaser, used in github workflows when we release a new version, has some issues we could fix. 

https://github.com/kubernetes-sigs/ingress2gateway/actions/runs/12506980670/job/34892781248

<img width="1401" alt="image" src="https://github.com/user-attachments/assets/8560156d-4fe4-4a89-8bde-2da2342e6b20" />

/good-first-issue

**Comment by subrajeet-maharana** [comment]
Can I work on this issue?
