### ISSUE TITLE
The Road to v0.1.0

### ISSUE THREAD

**Issue by Xunzhuo** [kubernetes-sigs/ingress2gateway#21]
Before v0.1.0, IMHO, we need to finish subtasks below:

### Codebase

- [ ] refactor code base to have a better extensible translator code structure.
- [ ] init basic testing abilities:
   - [ ] unit test
   - [ ] coverage test
   - [ ] e2e test
- [ ] add support for version output in cmd
- [ ] add support for different resource mode: `local` and `remote`, to support translating Ingress from files besides from the clusters.
 - [ ] add support for filtering different GWAPI Resources in output
 - [x] add support for different output type: `json` and `yaml`.

### Toolings

- [ ] refactor toolings: make file, hack script to have an extensible/powerful structure.
- [ ] provide detailed `make help`
- [ ] provide `Golang` area make targets to build and test golang, including:
  - [ ] `make build`: support building host OS and Arch binary.
  - [ ] `make build-multiarch`: support building multiarch binaries of i2gw: `linux/amd64`, `linux/arm64`, `darwin/amd64`, `darwin/arm64`.
  - [x] `make test`: support running unit test of i2gw.
  - [ ] `make format`: check if go module is clean and runs go mod tidy.
  - [ ] `make clean`: clean output files.
- [ ] provide `Image` area make targets (We do not plan to publish i2gw in image, but this area is needed for developers who want to have local build and push i2gw image and host it privately), including:
  - [ ] `make image`: build host OS and Arch image.
  - [ ] `make image-multiarch`: build multi-arch: `linux/arm64` and `linux/amd64` image with docker buildx.
  - [ ] `make push`: build and push host OS and Arch image.
  - [ ] `make push-multiarch`:  build and push multi-arch: `linux/arm64` and `linux/amd64` binary with docker buildx.
- [ ] provide `Lint` area make targets used for linting codes, including:
  - [ ] `make lint`: Run all linter of code sources, including golint, yamllint, and codespell.
  - [ ] `make lint-deps`: Prepare everything necessary to lint

### CI

- [ ] Build and Test Workflow: 
  - [ ] runs test: unit test, e2e test of i2gw. (The e2e is not urgent I think, because i2gw will support read Ingress from files, so core translation logics can be tested by unit test from reading files. But e2e may needed in the future, need more thoughts on this topic)
  - [ ] runs linters: golint, yamllint, codespells.
  - [ ] runs multi-arch build of i2gw.
- [ ] Release Workflow: 
  - [ ] support automatcally build and publish i2gw multi-arch binaries when pushing a new tag.
- [ ] Latest Release Workflow:
  - [ ] Automatically create latest tag and release for using latest verson of i2gw.

### Document

- [ ] Update Installation Docs
- [ ] Update Development Docs
- [ ] Update Release Docs
- [ ] Update Quickstart Docs

### Project

- [ ] Add PR template
- [ ] Add Issue template

### Installation

- [x] Build from Source
- [x] Download from GitHub Release
- [ ] Kubernetes Krew Plugin
- [ ] Install script

### Design

- [x] How to handle different Implementations(Providers) and make codes extensible, provides some interfaces for implementations.
- [ ] ....

**Comment by Xunzhuo** [comment]
https://github.com/kubernetes-sigs/ingress2gateway/pull/19 https://github.com/kubernetes-sigs/ingress2gateway/pull/20 https://github.com/kubernetes-sigs/ingress2gateway/pull/12 https://github.com/kubernetes-sigs/ingress2gateway/pull/13 https://github.com/kubernetes-sigs/ingress2gateway/pull/16 https://github.com/kubernetes-sigs/ingress2gateway/pull/17 https://github.com/kubernetes-sigs/ingress2gateway/pull/18 https://github.com/kubernetes-sigs/ingress2gateway/pull/11 https://github.com/kubernetes-sigs/ingress2gateway/pull/10

**Comment by Treenhan** [comment]
I would like to work on https://github.com/kubernetes-sigs/ingress2gateway/issues/24

**Comment by mlavacca** [comment]
v0.1 is already out.

/close
