### ISSUE TITLE
Add support for different resource mode: local and remote, to support translating Ingress from files besides from the clusters.

### ISSUE THREAD

**Issue by Treenhan** [kubernetes-sigs/ingress2gateway#24]
**What would you like to be added:**
Add support for different resource mode: local and remote, to support translating Ingress from files besides from the clusters.

**Comment by Treenhan** [comment]
Can I get assigned @LiorLieberman ?

**Comment by LiorLieberman** [comment]
@Treenhan are you planning to do any additional work on this issue?

**Comment by mlavacca** [comment]
As far as I get from this issue's intention, this feature is already implemented. Do you agree we can close it?

@LiorLieberman 
@levikobi

**Comment by levikobi** [comment]
@mlavacca Yes so it looks

**Comment by LiorLieberman** [comment]
we do not have "remote" support. i.e reading from github(without cloning) . but I dont think anyone ever asked for it so we can close for now
