### ISSUE TITLE
Support namespace filtering when reading from files

### ISSUE THREAD

**Issue by Treenhan** [kubernetes-sigs/ingress2gateway#37]
The idea is when running ingress2gateway command, we should be able to specify which namespace we want to use. If a namespace is explicitly specified, the command will only process the Ingress resources within that namespace. However, if no namespace is provided, the command will process Ingress resources across all namespaces.

/kind feature
/kind test

**Comment by levikobi** [comment]
Hi @Treenhan,
I think we should keep the same functionality for reading from a file as reading from the cluster.
At the moment, when reading from the cluster without specifying a namespace you will only process objects from the current active namespace, as opposed to all the namespaces. 
If you want to read from all namesapces, you have a --all-namespaces flag.

**Comment by LiorLieberman** [comment]
@Treenhan whats the status of it? do you have any blockers you need help with?

**Comment by Treenhan** [comment]
I'm still deciding what the default behavior should be if no namespace is specified in the YAML/JSON files. I assume that not all machines converting these files will have access to cluster information, or they don't have a cluster at all but just want to convert the files. So they won't be able to grab the default namespace from the cluster context.

My thinking is that the default behavior should be to read everything, unless users want to choose a specific namespace. The reason is that without cluster context, there's no way to know what the default namespace should be.

@LiorLieberman @levikobi any ideas?

**Comment by Treenhan** [comment]
I think I will go with this:
- Without any flag, use the namespace in the active context, if there is no context, it will convert all (this allows users to use this tool without having kubernetes running)
- Use --all-namespaces to convert all
- Use  --namespace X to filter out specific namespaces

**Comment by levikobi** [comment]
> I think I will go with this:
> - Without any flag, use the namespace in the active context, if there is no context, it will convert all (this allows users to use this tool without having kubernetes running)
> - Use --all-namespaces to convert all
> - Use  --namespace X to filter out specific namespaces

Sounds good to me @Treenhan !

**Comment by LiorLieberman** [comment]
+1 sgtm

**Comment by Treenhan** [comment]
This is now done in https://github.com/kubernetes-sigs/ingress2gateway/pull/43
