### ISSUE TITLE
Document i2gw interpretation of Ingress annotations/fields

### ISSUE THREAD

**Issue by sunjayBhatia** [kubernetes-sigs/ingress2gateway#4]
A document explaining how each field/annotation of an Ingress/other resource will be treated when turned into Gateway API configuration (e.g. what set of listeners/routes gets created when an Ingress has a `defaultBackend`) seems useful for users/contributors.

The tests are a great place to learn this but for a user who might not want to read through them, this could be more discoverable and a good way to get agreement from contributors.

**Comment by sunjayBhatia** [comment]
Part of this is maybe documenting/implementing this: https://github.com/kubernetes-sigs/ingress2gateway/pull/3#discussion_r1005087651

The order we process Ingress resources will likely matter to the output, e.g. if multiple resources specify a `defaultBackend` or route for a host/path we need conflict resolution rules

**Comment by sunjayBhatia** [comment]
Heres some WIP just added to the README: https://github.com/kubernetes-sigs/ingress2gateway/pull/5

**Comment by robscott** [comment]
This was fixed by #5, thanks @sunjayBhatia!
