### ISSUE TITLE
Add support for running only some of the providers 

### ISSUE THREAD

**Issue by levikobi** [kubernetes-sigs/ingress2gateway#45]
**What would you like to be added**:
Add a new flag that enables users to choose which concrete providers should be used when executing the 'print' command.

1. By default, all providers should be used.
2. A user should be able to choose more than one provider.

We can start working on it after #40 is merged.

**Comment by jeffyjf** [comment]
/assign
I want to try it

**Comment by levikobi** [comment]
Thanks @jeffyjf!
Please keep in mind we can start working on it only after #40 is merged.
Let me know if I can be of any help, and if you have any questions? And thank you for your interest in this project!

**Comment by jeffyjf** [comment]
You are welcome. Thanks for giving us newbies a opportunity to contribute codes to the community. I will pay attention to the pr #40 and learn more knowledge about gateway api in the next several days.
