### ISSUE TITLE
CI - Add multi arch release workflow

### ISSUE THREAD

**Issue by levikobi** [kubernetes-sigs/ingress2gateway#47]
**What would you like to be added**:
Add an automated release workflow, whenever creating a new tag with a 'v' prefix.

**Comment by LiorLieberman** [comment]
I believe this one is addressed by https://github.com/kubernetes-sigs/ingress2gateway/pull/54 right ?

I am closing it for now but do open it if you meant to something else.

**Comment by levikobi** [comment]
It looks like our release has all major OS & architectures covered, so yes it's done 👍
