### ISSUE TITLE
Support fetching ingress resources form github for conversion

### ISSUE THREAD

**Issue by Treenhan** [kubernetes-sigs/ingress2gateway#49]
This functionality is similar to reading from a file, but from GitHub (remote source) instead of local. Before this can be done, please refactor the code to have the DataSource struct, which represents the ingresses in general, then create the interface with the method getIngressList() which can be used in `print.go`. Different DataSource (remote, local, cluster) has their own interface implementation.

**Comment by Treenhan** [comment]
/kind feature

Can I get assigned @LiorLieberman ?

**Comment by mlavacca** [comment]
Is there still any intention/desire to have this feature or can we close this issue?

@Treenhan @LiorLieberman @levikobi

**Comment by LiorLieberman** [comment]
The idea is nice, but I do not think we have a need for it now. 
I am closing it now and we will revisit in the future if we ever get a feature request to support more data sources
