### ISSUE TITLE
Investigate commonly used nginx ingress annotations

### ISSUE THREAD

**Issue by Treenhan** [kubernetes-sigs/ingress2gateway#52]
Currently, only a small set of nginx ingress annotations are supported. We would like to:

- [ ] Investigate and document what are the the most important and commonly used annotations from the complete list available at https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/
- [ ]  Create separate issues to support different logical groups of annotations (meaning the tool can parse them and convert them into similar gateway/HTTPRoute features)
- [ ] Explain how the conversion process works in our documentation.

/kind feature

**Comment by Treenhan** [comment]
@LiorLieberman can I get assigned?

**Comment by LiorLieberman** [comment]
@Treenhan made some changes to the description and the title. FYI. 

/triage accepted

**Comment by LiorLieberman** [comment]
@Treenhan just checking in, do you still plan to work on this ? Let us know if you need any help

**Comment by Treenhan** [comment]
Hi @LiorLieberman, I think this feature is not as important as it used to be now that v0.1.0 is released, I will deprioritize this and focusing on fixing issues.
