### ISSUE TITLE
ingress-nginx: Canary Weight Total Flawed

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/ingress2gateway#6]
As caught by @sunjayBhatia, although we parse the `nginx.ingress.kubernetes.io/canary-weight-total` annotation, we have significant issues with the implementation.

1. We [ignore any error when trying to convert the value of this annotation to an int](https://github.com/kubernetes-sigs/ingress2gateway/blob/a2ba9cdbf470a0b32c8040650193897eef2ab3ef/pkg/i2gw/aggregator.go#L415). This should be bubbled up to the list of errors we return when using the tool. 
2. We don't use `weightTotal` anywhere. Although we populate `weightTotal` with the value of this annotation, we don't actually use it anywhere else in the code. This should be used to calculate the weight assigned to other backends in the same HTTPRoute.
3. We don't have any test coverage for this feature.

These items can either all be fixed in the same PR, or smaller individual PRs depending on what's easiest.

**Comment by levikobi** [comment]
Can I take this issue?
