### ISSUE TITLE
Add Kong provider

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/ingress2gateway#63]
**What would you like to be added**:

We'd like to add a new provider to convert ingress resources in setups that use the [Kong Kubernetes Ingress Controller](https://github.com/Kong/kubernetes-ingress-controller). 

**Why this is needed**:

This is needed to give the Kong Kubernetes Ingress Controller users a tool to migrate from Ingress API to Gateway API.

**Comment by mlavacca** [comment]
@robscott @LiorLieberman I'd like to start working on this soon. Does it sound good to you?

**Comment by LiorLieberman** [comment]
sounds great, thanks @mlavacca ! let me know if you need help
/assign @mlavacca
