### ISSUE TITLE
Add Higress Provider

### ISSUE THREAD

**Issue by Xunzhuo** [kubernetes-sigs/ingress2gateway#64]
**What would you like to be added**:

We'd like to add a new provider to convert ingress resources in setups that use the [Higress](https://github.com/alibaba/higress) Ingress APIs.

**Why this is needed**:

MIgrate Higress Ingresses to Gateway APIs.

**Comment by Xunzhuo** [comment]
/assign

Assign myself to work on this in the future.

**Comment by LiorLieberman** [comment]
Hi @Xunzhuo , just checking in. Let me know if you need any help moving this forward,

**Comment by mlavacca** [comment]
Hi @Xunzhuo, this is a friendly ping.
Is there any intention to move this issue forward and implement the provider?

**Comment by Xunzhuo** [comment]
Hey forks, my bandwidth is limited recently, I would like to ping Higress community to see if there is anyone want to try this.

Thanks
