### ISSUE TITLE
Create makefile with "make verify"

### ISSUE THREAD

**Issue by robscott** [kubernetes-sigs/ingress2gateway#7]
We should have a verify task that runs go tests and golangci-lint. As part of this, we should copy over the following files from Gateway API:

- https://github.com/kubernetes-sigs/gateway-api/blob/main/.golangci.yml
- https://github.com/kubernetes-sigs/gateway-api/blob/main/hack/verify-golint.sh

It may be useful to look at the Makefile from Gateway API when working on this as this one will likely be a subset of that:

- https://github.com/kubernetes-sigs/gateway-api/blob/main/Makefile

**Comment by shouri007** [comment]
I can take this up

**Comment by shaneutt** [comment]
Thanks @shouri007! Let us know if you need any help.
