### ISSUE TITLE
print all resources when reading from files

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/ingress2gateway#73]
**What would you like to be added**:
When thinking about how this tool would be used in a real environment, we can have a user willing to convert a set of yaml files that use ingress resources into the same set of yaml files using gateway resources. As of today, when the flag `input_file` is used, the tool gets only the ingress resources and prints the converted ones.

When a user has a yaml file containing ingress resources and other kinds of resources (deployment, services, ...), a simple one-liner could enable an immediate conversion to have a ready-to-use file.

For example, by performing an operation similar to the following:
```bash
./ingress2gateway print --input_file old_file.yaml -A --providers=kong --print-all-resources > new_file.yaml
``` 
a user can have a new yaml file ready-to-use.

**Comment by mlavacca** [comment]
@robscott @LiorLieberman I'd like to start working on it as soon as possible. Does it work for you?

**Comment by LiorLieberman** [comment]
sweet. Sounds good to me, thanks!
/assign @mlavacca
