### ISSUE TITLE
Annotation translation when Gateway API feature does not exist

### ISSUE THREAD

**Issue by mlavacca** [kubernetes-sigs/ingress2gateway#74]
**What would you like to be added**:

The README.md clearly states: "Note: Ingress2gateway is not intended to copy annotations from Ingress to Gateway API.".
Nevertheless, if a complete provider needs to be implemented, some annotations may require to be copied from ingress resources into gateway API ones.

An example is features not provided by the Gateway API or implementation-specific features. For these cases, a 1:1 translation between ingress annotations to gateway annotations would be beneficial to the tool itself.

**Comment by robscott** [comment]
I think the goal here was to encourage the functionality to just be added to Gateway API instead of adding/encouraging annotations on Gateway API. With that said, I think it's probably fair to support this for features that are clearly implementation-specific and out of scope for Gateway API.

**Comment by LiorLieberman** [comment]
+1
I think the scope of supporting such feature should also include some guidance. Something like "Start a discussion in Gateway API to see whether this feature can go as a Gateway API feature (gateway also have implementation features) if not, open the PR here and link to your Gateway API discussion.

thougts?
