### ISSUE TITLE
Add a `--kubeconfig` flag to specify kubeconfig file location

### ISSUE THREAD

**Issue by levikobi** [kubernetes-sigs/ingress2gateway#81]
**What would you like to be added**:
Add a `--kubeconfig` flag to specify kubeconfig file location.

**Why this is needed**:
Some users and organizations work with multiple Kubernetes clusters by utilizing multiple config files instead of one. The --kubeconfig flag allows you to switch between these clusters by specifying different configuration files.

**Comment by LiorLieberman** [comment]
/remove-lifecycle stale
@levikobi please update if you still work on this. If not maybe mark it as help wanted

**Comment by YTGhost** [comment]
Hi, I'm interested in this issue.
/assign
