### ISSUE TITLE
Add instructions for writing release-notes in PR. 

### ISSUE THREAD

**Issue by LiorLieberman** [kubernetes-sigs/ingress2gateway#84]
/kind documentation

Add instructions for writing release-notes in PR. 

We are using [Kubernetes Release Notes Generator](https://github.com/kubernetes/release/blob/master/cmd/release-notes/README.md#kubernetes-release-notes-generator) to generate our release notes. We should incorporate the instructions for how to write them in the PR template.

/help-wanted
/good-first-issue

**Comment by prashantrewar** [comment]
I want to do this can you please guide me for this issue.  I am a beginner.

**Comment by prashantrewar** [comment]
Thank you so much @LiorLieberman 

But in the [PR template](https://github.com/kubernetes-sigs/ingress2gateway/blob/main/.github/PULL_REQUEST_TEMPLATE.md?plain=1),  release-notes already there and what additional `kind` you want to add.

**Comment by LiorLieberman** [comment]
I think we need to clarify to the author the importance of picking the right kind and the writing the correct release notes if needed. If the author does not follow that, it makes the changelog generation a bit messy and error pruning.

So something like `Heads up - the release notes and the kind are going to be used to generate the right Changelog for the release. To make sure your contribution is recognized, please pick the right kind and add the release notes when necessary`

Its just a draft out of my head now, I am sure you will come up with something better then this.

**Comment by prashantrewar** [comment]
Hey @LiorLieberman, I created a PR for this issue, could you please take a look?
