### ISSUE TITLE
Add Consul ingress gateway provider

### ISSUE THREAD

**Issue by mikemorris** [kubernetes-sigs/ingress2gateway#90]
**What would you like to be added**:
Add a [provider](https://github.com/kubernetes-sigs/ingress2gateway/blob/main/PROVIDER.md) to translate from [Consul ingress gateway](https://developer.hashicorp.com/consul/docs/connect/config-entries/ingress-gateway#complete-configuration) CRDs to Gateway API CRDs for [Consul API Gateway on Kubernetes](https://developer.hashicorp.com/consul/docs/api-gateway).

**Why this is needed**:
To ease the migration path to a more full-featured ingress implementation.

/cc @nathancoleman @david-yu

**Comment by levikobi** [comment]
Awesome @mikemorris, thank you!
Feel free to reach out if you encounter any problems

**Comment by nathancoleman** [comment]
Great idea @mikemorris !

**Comment by LiorLieberman** [comment]
Hey 👋  just checking in, is anyone plan to work on this soon?

**Comment by swastik959** [comment]
I would like to give it a try 
/assign

**Comment by prakrit55** [comment]
@LiorLieberman, I would like to give it a try

**Comment by swastik959** [comment]
- Hi @prakrit55 I am actually working on it and will raise a pr soon

**Comment by mlavacca** [comment]
Hi @swastik959, how is it going with this issue? In case you need any help, please let us know
